### ISSUE TITLE
[PE-D][Tester A] Button in the help menu has truncated text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-4/tp#127]
On MacOS, when the `Help` section is opened using the TrAcker menu bar, the button next to the UG link has it's text truncated to `Copy U...`.

Note that this only happens when the `Help` floating menu is in focus. When focus is on another window or application, the button text is no longer truncated.

**Truncated, in focus**

![image.png](https://raw.githubusercontent.com/AdityaB4/ped/main/files/9fd9b0c7-d4fc-496a-afc8-e46eb03b0398.png)

**Not truncated, not in focus (clicked on this browser window before taking screenshot)**

![image.png](https://raw.githubusercontent.com/AdityaB4/ped/main/files/2fb5bdbc-7fe9-4eef-93ee-42dec1ea3f95.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: AdityaB4/ped#1

**Comment by wongkj12** [comment]
Not a bug, user can still see the text when help window is in focus.
