### ISSUE TITLE
[PE-D][Tester A] User Guide mentions "...AddressBook will discard all data..."

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-4/tp#130]
Inside the callout, under the `Editing the data file` sub-heading, the text reads "Caution: If your changes to the data file makes its format invalid, **AddressBook** will discard all data...".

This is the base products name, and could be changed to reflect TrAcker instead.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: AdityaB4/ped#2

**Comment by wang-xinrong** [comment]
Addressed
