### ISSUE TITLE
[PE-D][Tester E] Does not return error or command result when empty string is passed in #1

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-4/tp#131]
Output for `find /n`:

![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/aefe7685-a164-4609-8391-1baeb2d7d8f4.png)

My terminal shows InvocationTargetException when I type in empty string, which is not handled by TrAcker :(

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yiwern5/ped#2

**Comment by wang-xinrong** [comment]
Addressed
