### ISSUE TITLE
[PE-D][Tester C] Find Function Does Not Properly Match Prefixes in Names, Allowing Partial Matches Anywhere in the Name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-4/tp#133]
As stated in the user guide, the find feature should match the prefixes of the input. But when a single letter is typed in as an input, it listed every person that has the letter anywhere in their name, e.g. find /n a will result in the result below.
![Screenshot 2024-04-05 at 16.12.16.png](https://raw.githubusercontent.com/menatahari/ped/main/files/4418cace-131c-490c-a6e8-195b6a92ec71.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: menatahari/ped#1

**Comment by kaitinghh** [comment]
Documentation bug, fixed
