### ISSUE TITLE
[PE-D][Tester E] Repeated command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-4/tp#140]
delete all command seems to work the same as clear command, maybe it would be good to provide clarity on the implementation of delete all command :D 

![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/adaaa821-df1d-4d49-b9bc-6f3f4f969a7a.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: yiwern5/ped#5

**Comment by wang-xinrong** [comment]
WIP

**Comment by wang-xinrong** [comment]
Addressed
