### ISSUE TITLE
[PE-D][Tester E] Unable to edit person when I break the program 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-4/tp#167]
Output for `edit 1 /n hi` after the program did not return command result due to invalid command (eg. `find /n`):
![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/8b550bc8-0395-47ff-855e-a8834b1df25e.png)

Output for `edit 1 /n hi` after exit the program and rerun:
![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/1eca858b-0742-44ed-9a50-8e928b3f14ae.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yiwern5/ped#13

**Comment by wang-xinrong** [comment]
Addressed
