### ISSUE TITLE
[PE-D][Tester E] Unable to delete person when I break the program

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-4/tp#169]
Output for `delete 1` after the program did not return command result due to invalid command (eg. `find /n`):
![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/985d03a0-a341-4502-9271-2898cda49b0b.png)

Output for `delete 1` after exit the program and rerun:
![image.png](https://raw.githubusercontent.com/yiwern5/ped/main/files/29947317-5baf-4013-85c3-9b22972b5e79.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yiwern5/ped#14

**Comment by wang-xinrong** [comment]
Behaviour bug to be fixed

**Comment by wang-xinrong** [comment]
Addressed
