### ISSUE TITLE
[PE-D][Tester C] 'available' Command Listed Both Available Student and TA in the Tutorial

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-4/tp#173]
The user guide mentions that the available feature will
>Filters all replacement TAs who are available for a specified tutorial group.

However, when the students' are tagged as available in the same tutorial group as the ta, typing the available command, will list out both students and tas available.

The command I typed in was `available /g 1` and the result is attached below.
![Screenshot 2024-04-05 at 18.26.32.png](https://raw.githubusercontent.com/menatahari/ped/main/files/722c87c6-13ba-4de5-91a1-29a34be4c646.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: menatahari/ped#8

**Comment by wang-xinrong** [comment]
Behaviour bug to be fixed

**Comment by wang-xinrong** [comment]
Addressed by Kotaro
