### ISSUE TITLE
[PE-D][Tester B] Possible bug for availability feature 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-4/tp#176]
![image.png](https://raw.githubusercontent.com/Chiarena/ped/main/files/248dc83b-4d95-4c1c-aa9d-e5198b04482b.png)
The tutorial slots can be assigned and set as available for a student. This could be a small bug since the purpose of adding the availability feature is for TAs to check the availability of other TAs. There seems to be little use for a tutorial slot to be assigned to a student.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Chiarena/ped#5

**Comment by wang-xinrong** [comment]
A bug to be fixed

**Comment by yyccbb** [comment]
Can consider adding the constraints in the UG
