### ISSUE TITLE
[PE-D][Tester B] Missing error message for removetag

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-4/tp#179]
Output of removetag 1 /t Assignment1:
![image.png](https://raw.githubusercontent.com/Chiarena/ped/main/files/61e7a006-0b79-414d-9870-c6a1a983eb36.png)

Originally, the student Bernice did not have a Assignment 1 tag. An error should be raised when the user tries to remove a tag from a student that was not originally tagged to the student, but instead it shows a success message. Thus could be an issue as users may be confused as to why their command does not seem to  be working despite the success message. 

Additionally,, the success message given can be more detailed, instead of just stating "Updated person" maybe you can consider stating something like "tag removed"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Chiarena/ped#8

**Comment by yyccbb** [comment]
Can clarify with Prof first
