### ISSUE TITLE
Edit command: should editting contact type be allowed?

### ISSUE THREAD

**Issue by yyccbb** [AY2324S2-CS2103T-T11-4/tp#37]
Should changing contact type (student/TA) be allowed for edit command?

**Comment by wongkj12** [comment]
Editing contact type may create some bugs (e.g. student with attendance and assignments being tracked changing to a TA might not make sense). 
I don't think its necessary yet as it is unlikely for TA to need to change student to TA / vice versa midway through the semester. If mistake in contact type was made at the start, it can be corrected by deleting and re-creating.

**Comment by yyccbb** [comment]
I agree. So the conclusion is that the contact type of a person should not be allowed to be edited.
