### ISSUE TITLE
Edit tags

### ISSUE THREAD

**Issue by yyccbb** [AY2324S2-CS2103T-T11-4/tp#4]
As a user, I can edit tags associated with each saved contact, so that I can track attendance information of students and availability information of TAs.

**Comment by wang-xinrong** [comment]
Currently how tags are added (as part of the Add command):
	- the CLI command requires each tag to be specified using /t
		- for example, if we are to add two tags to the person, we need to do 
			add ... /t tag1 /t tag2
	- implementation-wise, the tags are stored in Set<Tag>, which is a hasheset
		- when add command is parsed, it calls ParserUtil::parseTags
			- which hashes input tags into the hashset tagSet
			- duplicates are removed in the hashing process

Proposed change:
	- "An alternative (arguably, a more OOP) model is given below. It has a Tag list in the AddressBook, which Person references. This allows AddressBook to only require one Tag object per unique tag, instead of each Person needing their own Tag objects." -- from DG
	- detailed implementation:
		- backward compatible:
			- when edit/add commands are run, and an existing tag is to be added, the corresponding command would cause the specified tag from UniqueTagList to be added to the person
			- when a new tag is specified, the new tag would be added to the UniqueTagList, before it is added to the person
		- new implementations:
			- allow creation of a tag without assigning it to any person
			- allow batch assign the tag to multiple person
			- allow accessing information regarding users sharing that tag from the tag itself.
				- e.g. for a particular assignment (tag), we can find person assigned with finished/unfinished
			- more customisable tag:
				- an assignment tag can have two status: DONE or NOT DONE
				
<img width="874" alt="image" src="https://github.com/AY2324S2-CS2103T-T11-4/tp/assets/48174229/2897405d-87e0-4dfd-abed-4a6d4eb43cf0">
UML diagram partially illustrating the proposed change, taken from DG of AB3

**Comment by yyccbb** [comment]
Because the primary function of tags (for v1.2) is weekly attendance tracking for students and availabilty tracking for TAs, each tag object needs to have an isMarked boolean attribute, which also means that tag objects cannot be shared across different contact entries. Therefore, the current structure should be preserved.

**Comment by wang-xinrong** [comment]
but we can also just expand the tag class to include two values such as DONE and NOT DONE, then person sharing the tag can have their identity being added to either the tag.done set or tag.not_done set. this could make future edition to the tag easier

**Comment by wang-xinrong** [comment]
After discussion, proposed implementation:

Ideal implementation for v1.2
Each person stores a Tag, all Tags of the same type would be stored to SuperTag for ease of batch edit/queries. All SuperTags would then be implemented by TagManager

<img width="539" alt="image" src="https://github.com/AY2324S2-CS2103T-T11-4/tp/assets/48174229/40a3c7aa-d142-42dc-a345-4ab94dbf93aa">

Ideal eventful implementation:
Each person would be able to directly store a reference to the SuperTag, which would include hashSet to store the person under different tagStatus hash sets. Again all the SuperTag would be managed by a TagManager

<img width="452" alt="image" src="https://github.com/AY2324S2-CS2103T-T11-4/tp/assets/48174229/b4d0eed3-a62e-4be7-a5cd-a94d4aa4612c">

**Comment by wang-xinrong** [comment]
### Actual Implementation in view of the time constraint and workload:

- each tag now has four possible TagStatus: 
1. COMPLETE_GOOD: complete before deadline
2. COMPLETE_BAD: complete after deadline
3. INCOMPLETE_GOOD: incomplete before deadline
4. INCOMPLETE_BAD: incomplete after deadline

- GUI now reflects the TagStatus of each tag using different colours (currently arbitrarily set, will update before finalising this PR)

- Mark command now implemented
1. takes the form of Mark {INDEX} /t {tagName} /ts {TagStatus}
2. updates the status of an existing tag if it exists -> implementation actually just creates a new tag
3. creates a new tag with specified status if the tag specified by tagName does not yet exist

### todos:
1. Write tests for MarkCommand and MarkCommandParser
2. Update AddressBookParser tests
3. Clear check style errors

**Comment by wang-xinrong** [comment]
Commands format:

mark {index} /t {tagName} /ts {tagStatus}

index: postive integers
tagName: String indicating tags to be added
    if {tagName} matches with existing tag, the tag would be updated
    if {tagName} does not match with any existing tag, a new tag of the tagName would be created
tagStatus: values from {"cg", "cb", "ig", "ib"}
    "cg" stands for COMPLETE_GOOD, meaning completed before deadline
    "cb" stands for COMPLETE_BAD, meaning completed after deadline
    "ig" stands for INCOMPLETE_GOOD, meaning not yet complete before deadline
    "ib" stands for INCOMPLETE_BAD, meaning not yet complete after deadline

sample commands:
    mark 1 /t assignment1 /ts cg
    mark 2 /t assignment2 /ts ig
